name: e2e tests

on:
  workflow_dispatch:
    

jobs:
  test-setup-v4:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
 
    env:
  
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_INSTALL_DIR: "./.dotnet"
      NUGET_AUTH_TOKEN: ${{secrets.GIT_TOKEN}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.x.x
          source-url: https://nuget.pkg.github.com/xxxx/index.json
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: node -e "const fs = require('fs');console.log(process.env.NUGET_AUTH_TOKEN); fs.writeFileSync('check.txt', process.env.NUGET_AUTH_TOKEN);"
      - run: cat check.txt
      - run: dotnet restore
      - run: dotnet build --no-restore


  test-setup-v3:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
 
    env:
  
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_INSTALL_DIR: "./.dotnet"
      NUGET_AUTH_TOKEN: ${{secrets.GIT_TOKEN}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x
          source-url: https://nuget.pkg.github.com/xxxx/index.json
      - run: dotnet restore
      - run: dotnet build --no-restore
